image: docker:24

options:
  docker: true

pipelines:
  branches:
    # Development branch
    dev:
      - step:
          name: CI for Dev 
          deployment: Development
          services:
            - docker
          script:
            - apk add --no-cache make 
            - export DOCKER_BUILDKIT=0
            - make build
            - make start
            - make db-wait
            - make test
            - make down

    # Main branch (Production)
    main:
      - step:
          name: CI for Main 
          deployment: Production
          services:
            - docker
          script:
            - apk add --no-cache docker-compose make 
            - export DOCKER_BUILDKIT=0
            - export ENABLE_VOLUME=""
            - make build
            - make start
            - make db-wait
            - make test
            - make down

    # QA branch (manual trigger)
    qa:
      - step:
          name: start tests and deploy to QA
          deployment: Quality Assurance
          trigger: manual
          services:
            - docker
          script:
            - apk add --no-cache docker-compose make 
            - export DOCKER_BUILDKIT=0
            - export ENABLE_VOLUME=""
            - make build
            - make start
            - make db-wait
            - make test
            - make down

    # Staging branch (manual trigger)
    staging:
      - step:
          name: start tests and deploy to Staging
          deployment: Staging
          trigger: manual
          services:
            - docker
          script:
            - apk add --no-cachedocker-compose make 
            - export DOCKER_BUILDKIT=0
            - export ENABLE_VOLUME=""
            - make build
            - make start
            - make db-wait
            - make test
            - make down
