#this file is for local testing
version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: week8-app:latest
    container_name: week8-app
    restart: always

    expose:
      - "8080"

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://0.0.0.0:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - app-network


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: week8-nginx:latest
    container_name: week8-nginx
    restart: always

    ports:
      - "8080:80"    # 本地访问 http://localhost:8080

    depends_on:
      app:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - app-network


networks:
  app-network:
    driver: bridge
