version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: week8-app:local
    container_name: week8-app
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: runtime-local
    image: week8-nginx:local
    container_name: week8-nginx-local

    ports:
      - "8080:80"

    depends_on:
      - app

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
