#a fix version
version: '3.8'

#define services here
services:
  #database service
  db:
    build: 
      context: .
      dockerfile: DockerfileA
    container_name: mysql_db
    #if this container stop, start again automatically
    restart: always
    #would use the environment we store in the bitbucket
    #when we push to different branches
    #MYSQL container need to know 
    environment:
    
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #mandatory
      MYSQL_DATABASE: ${MYSQL_DATABASE} #recommended
      MYSQL_USER: ${MYSQL_USER} #recommended
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} #recommended
    #default db ports
    ports:
      - "3306:3306"
    #the required docker volumne mount strategy
    volumes:
    #use the data stored before 
      - db_data:/var/lib/mysql
    #mount my init.sql in mysql to the docker file which will execute by the image automatically
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    #useful when other services need to depend on this 
    #run after mysql start running, and mark service healthy or not healthy
    #healthcheck for docker orchestration level
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      #run test every 5s
      interval: 5s
      #wait for test finish
      timeout: 3s
      #healthy if successful within 5s
      retries: 5

  api:
    #need to build based on the image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "3000:3000"
    #it needs mysql to be healthy to run successfully
    depends_on:
      db:
        condition: service_healthy
    #need this to connect to db
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    #overwrite cmd in docker file
    command: ["sh", "-c", "./wait-for.sh db && node app.js"]

#persistent data storage
#\\wsl$\docker-desktop-data\data\docker\volumes\db_data\_data\
volumes:
  db_data: