#basic shell satisfy all the need for builder
FROM public.ecr.aws/docker/library/alpine:3.20 AS builder
WORKDIR /config
#because the docker compose will change to deploy nginx dir
COPY default.conf .

#change the default.config in the image be my default.conf
#image with only low vul
FROM public.ecr.aws/docker/library/nginx:stable-alpine3.22
COPY --from=builder /config/default.conf /etc/nginx/conf.d/default.conf
#non root user 
USER nginx
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]