#basic shell satisfy all the need for builder
FROM alpine:3.20 AS builder

WORKDIR /config
#because the docker compose will change to deploy nginx dir
COPY default.conf .

#change the default.config in the image be my default.conf
#image with only low vul
FROM nginx:1.29.3-alpine3.22
COPY --from=builder /config/default.conf /etc/nginx/conf.d/default.conf
#non root user 
USER nginx
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]