#the request go to 80 will proxy to 5000 the api container for further action
events {}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://api:5000;
        }
        location /health {
            proxy_pass http://api:5000/health;
        }
    }
}
