{
 "title": "Client Domain System Dashboard",
 "tags": [ "client-domains" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Select Client",
    "query": {}
   },
   {
    "name": "action",
    "label": "Select Action",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Error logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, client, action, error_message\n| filter @message like /failure/\n| parse @message /\"client\":\\s*\"?(?<client>[^\",}]+)\"?/\n| parse @message /\"action\":\\s*\"?(?<action>[^\",}]+)\"?/\n| parse @message /\"error_message\":\\s*\"?(?<error_message>[^\"{}]+)\"?/\n\n| filter client =~ /$client/\n| filter action =~ /$action/\n\n| sort @timestamp desc\n| limit 10",
     "logGroups": [
      {
       "accountId": "314146318322",
       "arn": "arn:aws:logs:ap-southeast-2:314146318322:log-group:/aws/lambda/client-domain-dns-function:*",
       "name": "/aws/lambda/client-domain-dns-function"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-southeast-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Successful VS Failed Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "Action": "$action", "Client": "$client" },
     "metricName": "SuccessCount",
     "namespace": "ClientDomainSystem",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "Action": "$action", "Client": "$client" },
     "metricName": "FailureCount",
     "namespace": "ClientDomainSystem",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Invocations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": { "FunctionName": "client-domain-dns-function" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "ap-southeast-2",
     "statistic": "Sum"
    }
   ]
  }
 ]
}