version: "3.8"
services:
  python-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-server
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_NAME: "inventory_db"
    depends_on:
      mysql-server:
        condition: service_healthy
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: inventory_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data:
